2ev/ejercicios/examen_roman_2ev/django/examen/incidencias/urls.py
from django.urls import path
from . import views

app_name = "incidencias"
urlpatterns = [
    path('listado/', views.listado, name='listado'),
    path('incidencias/<int:id>/<int:ide>/', views.formulario, name='formulario'),
]

2ev/ejercicios/examen_roman_2ev/django/examen/incidencias/models.py
from django.db import models

# Create your models here.
class Linea(models.Model):
    nombre = models.CharField(max_length=200, null=False)
    color = models.CharField(max_length=200)
    distancia = models.IntegerField()
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.nombre

class Estacion(models.Model):
    nombre = models.CharField(max_length=200, null=False)
    lineas = models.ForeignKey(Linea, on_delete=models.CASCADE, related_name='lineas')

    def __str__(self):
        return self.nombre

class Incidencia(models.Model):
    texto = models.CharField(max_length=200)
    fecha = models.DateTimeField(null=False)
    estaciones = models.ForeignKey(Estacion, on_delete=models.CASCADE, related_name='estaciones')

    def __str__(self):
        return f"{self.estaciones} {self.texto}"

2ev/ejercicios/examen_roman_2ev/django/examen/incidencias/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Linea, Estacion, Incidencia
from django.urls import reverse

# Create your views here.
def listado(request):
    lineas = Linea.objects.all()
    estaciones = Estacion.objects.all()
    return render(request, "incidencias/listado.html", {
        "lineas" : lineas,
        "estaciones" : estaciones
    })

def formulario(request, id, ide):
    linea = Linea.objects.get(id=id)
    estacion = Estacion.objects.get(id=ide)
    return render(request, "incidencias/formulario.html", {
        "estacion" : estacion,
        "linea" : linea
    })

def envio(request, id, ide):
    linea = Linea.objects.get(id=id)
    estacion = Estacion.objects.get(id=ide)
    try:
        texto = Incidencia.estaciones.get(id=request.POST["texto"])
    except(KeyError, Incidencia.DoesNotExist):
        return render(request, "mercado/detalle.html", {
            "linea" : linea,
            "estacion" : estacion,
            "error" : "Error al enviar"
        })
    else:
        texto.texto = request.POST["texto"]
        texto.save()

        return HttpResponseRedirect(reverse('mercado:resultados', args=(estacion.id,)))

2ev/ejercicios/examen_roman_2ev/django/examen/incidencias/templates/incidencias/formulario.html
<h1>{{estacion.nombre}} ({{linea.nombre}})</h1>
<form action="{% url 'incidencias:envio' linea.id estacion.id %}" method="post">
    {% csrf_token %}
    {% if error %}<p>{{error}}</p>{% endif %}
    <input type="text" name="texto">
        
    <input type="submit" value="enviar">
</form>

2ev/ejercicios/examen_roman_2ev/django/examen/incidencias/templates/incidencias/listado.html
{% for linea in lineas %}
    {% for estacion in estaciones %}
        {{ linea.nombre }} - {{ estacion.nombre }} <a href="{% url 'incidencias:formulario' linea.id estacion.id %}">+ Nueva incidencia</a><br>
    {% endfor %}
{% endfor %}