2ev/ejercicios/examen_2ev_casita/django/examen/examen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('incidencias/', include('incidencias.urls')),
    path('admin/', admin.site.urls),
]

2ev/ejercicios/examen_2ev_casita/django/examen/incidencias/urls.py
from django.urls import path

from . import views

app_name = "incidencias"
urlpatterns = [
    path('listado/', views.listado, name='listado'),
    path('incidencia/<int:id>', views.incidencia, name='incidencia'),
    path('exito/', views.exito, name='exito'),
]

2ev/ejercicios/examen_2ev_casita/django/examen/incidencias/models.py
from django.db import models

# Create your models here.
class Linea(models.Model):
    nombre_linea = models.CharField(max_length=200, null=False)
    color = models.CharField(max_length=200)
    distancia = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.nombre_linea}"

class Estacion(models.Model):
    nombre_estacion = models.CharField(max_length=200, null=False)
    linea = models.ForeignKey(Linea, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nombre_estacion}"

class Incidencia(models.Model):
    texto = models.CharField(max_length=500)
    fecha = models.DateTimeField('fecha y hora', null=False)
    nombre_estacion = models.ForeignKey(Estacion, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nombre_estacion} ({self.nombre_estacion.linea}) {self.texto}"

2ev/ejercicios/examen_2ev_casita/django/examen/incidencias/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from .models import Linea, Estacion, Incidencia


def listado(request):
    lineas = Linea.objects.all()
    estaciones = Estacion.objects.all()
    return render(request, "incidencias/listado.html", {
        "lineas" : lineas,
        "estaciones" : estaciones
    })
    
def incidencia(request, id):
    estacion = get_object_or_404(Estacion, id=id)
    texto_incidencia = request.POST.get('texto_incidencia', False)

    if texto_incidencia:
        incidencia = Incidencia(texto=texto_incidencia, fecha=timezone.now(), nombre_estacion=Estacion.objects.get(id=id))
        incidencia.save()

        return HttpResponseRedirect(reverse('incidencias:exito'))
    else:
        return render(request, 'incidencias/incidencia.html', {
            'estacion': estacion,
            'error': 'campo vacío'
        })

def exito(request):
    return render(request, 'incidencias/listado.html', {
        'lineas' : Linea.objects.all(),
        'estaciones': Estacion.objects.all(),
        'mensaje_exito': '--- Su incidencia ha sido dada de alta ---'
    })

2ev/ejercicios/examen_2ev_casita/django/examen/incidencias/templates/incidencias/incidencia.html
<h1>{{estacion.nombre_estacion}} ({{estacion.linea}})</h1>
<form action="" method="post">
    {% csrf_token %}
    {% if error %}<p style="color: red">{{error}}</p>{% endif %}
    <textarea name="texto_incidencia" cols="30" rows="10"></textarea>
        
    <input type="submit" value="submit">
</form> 

2ev/ejercicios/examen_2ev_casita/django/examen/incidencias/templates/incidencias/listado.html
<h2>Listado</h2>
{% for linea in lineas %}
    {% for estacion in linea.estacion_set.all %}
        {{ linea.nombre_linea }} - {{ estacion.nombre_estacion }} <a href="{% url 'incidencias:incidencia' estacion.id %}">+ Nueva incidencia</a><br>
    {% endfor %}
{% endfor %}

{% if mensaje_exito  %}{{mensaje_exito}}{% endif %}